//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Domain.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int PayrollId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> SSS { get; set; }
        public Nullable<decimal> Philhealth { get; set; }
        public Nullable<decimal> Pagibig { get; set; }
        public Nullable<decimal> NetPay { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
